### ISSUE TITLE
facade_maskrcnn.rar

### ISSUE THREAD

**Issue by LCsee** [wangyuefeng2017/LoD3Framework-#1]
I can't find the facade_maskrcnn.rar. Hope you can point out the location. Thank you very much!

**Comment by wangyuefeng2017** [comment]
You can download the instance segmentation weights file from the link (https://drive.google.com/drive/folders/1PgR3OMujgK-_J67Ml7gYVbQ0YSdFR0Gd). You can also train a more accurate model yourself using SAM.

**Comment by LCsee** [comment]
Thank you very much for your response. I have understood the points you made, and I will close the issue.

Wishing you good health and success in your work.
